### ISSUE TITLE
How to use G-suite account login

### ISSUE THREAD

**Issue by festum** [foxythemes/jira-cli#23]
Is there any key in `.jira-cli.json` for login with Google account?

**Comment by miguelmich** [comment]
@festum I also have enabled my personal JIRA account with G-Suite but for the rest API I need to use my JIRA username instead of my email, maybe this could give you more information: https://community.atlassian.com/t5/Jira-questions/REST-SSO-Atlassian-Account-JIRA/qaq-p/580736

Try with your username and let me know if it works :)

**Comment by festum** [comment]
@miguelmich Thanks for the info. I figured out the only way to get work is reset Atlassian password.:)

**Comment by simenandre** [comment]
AFAIK you don't have to use your Atlassian password. You can use [API Tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html) as password, not sure about usernames (probably your username). 

More information on #35

**Comment by jtprince** [comment]
@cobraz - My atlassian profile is linked to my G-suite account (i.e., I have no username and password). Based on the above comments, I found that this works:

username: \<My G-suite email address\>
password: an api token

Adding it here in case someone stumbles upon it (like I did, looking for how to get this working).
